module("resmng", package.seeall)


local BasePath = "data/"
do_load("reschk")


--------------------------------------------------------------------------------
do_load(BasePath .. "prop_cron")

do_load(BasePath .. "define_resource")
do_load(BasePath .. "define_arm")
do_load(BasePath .. "define_build")
do_load(BasePath .. "define_world_unit")
do_load(BasePath .. "define_buff")
do_load(BasePath .. "define_skill")
do_load(BasePath .. "define_hero_basic")
do_load(BasePath .. "define_hero_cure")
do_load(BasePath .. "define_hero_lv_exp")
do_load(BasePath .. "define_hero_quality")
do_load(BasePath .. "define_hero_skill_exp")
do_load(BasePath .. "define_hero_star_up")
do_load(BasePath .. "define_union_power")
do_load(BasePath .. "define_item")
do_load(BasePath .. "define_union_tech")
do_load(BasePath .. "define_union_donate")
do_load(BasePath .. "define_union_buildlv")
do_load(BasePath .. "define_union_task")
do_load(BasePath .. "define_union_award")
do_load(BasePath .. "define_union_mall")
do_load(BasePath .. "define_resm")
do_load(BasePath .. "define_tech")
do_load(BasePath .. "define_genius")
do_load(BasePath .. "define_task_detail")
do_load(BasePath .. "define_equip")
do_load(BasePath .. "define_online_award")
do_load(BasePath .. "define_citybuildview")
do_load(BasePath .. "define_citybuildview")
do_load(BasePath .. "define_boss_mod_by_date")
do_load(BasePath .. "define_boss_unlock")
do_load(BasePath .. "define_boss_level")
do_load(BasePath .. "define_tw_consume")
do_load(BasePath .. "define_tw_stage")
do_load(BasePath .. "define_kw_stage")
do_load(BasePath .. "define_level")
do_load(BasePath .. "define_task_daily")
do_load(BasePath .. "define_task_daily_award")
do_load(BasePath .. "define_kw_officer")
do_load(BasePath .. "define_monster_city")
do_load(BasePath .. "define_mc_stage")
do_load(BasePath .. "define_black_market")
do_load(BasePath .. "define_black_market_hot")
do_load(BasePath .. "define_black_market_hot_group")
do_load(BasePath .. "define_lt_stage")
do_load(BasePath .. "define_lt_reward")
do_load(BasePath .. "define_gacha_group")
do_load(BasePath .. "define_gacha_piont")
do_load(BasePath .. "define_gacha_gacha")
do_load(BasePath .. "define_gacha_world_limit")
do_load(BasePath .. "define_mall")
do_load(BasePath .. "define_union_god")
do_load(BasePath .. "define_language")
do_load(BasePath .. "define_open_field")
do_load(BasePath .. "define_altar_buff")
do_load(BasePath .. "define_vip")
do_load(BasePath .. "define_mall_item")
do_load(BasePath .. "define_mall_group_kw")
do_load(BasePath .. "define_mall_refresh")
do_load(BasePath .. "define_mall_group_manor")
do_load(BasePath .. "define_mall_group_monster")
do_load(BasePath .. "define_mall_group_relic")

do_load(BasePath .. "prop_arm")
do_load(BasePath .. "prop_build")
do_load(BasePath .. "prop_world_unit")
do_load(BasePath .. "prop_buff")
do_load(BasePath .. "prop_effect_type")
do_load(BasePath .. "prop_skill")
do_load(BasePath .. "prop_hero_basic")
do_load(BasePath .. "prop_hero_cure")
do_load(BasePath .. "prop_hero_lv_exp")
do_load(BasePath .. "prop_hero_quality")
do_load(BasePath .. "prop_hero_skill_exp")
do_load(BasePath .. "prop_hero_star_up")
do_load(BasePath .. "prop_union_power")
do_load(BasePath .. "prop_item")
do_load(BasePath .. "prop_union_tech")
do_load(BasePath .. "prop_union_donate")
do_load(BasePath .. "prop_union_buildlv")
do_load(BasePath .. "prop_union_task")
do_load(BasePath .. "prop_union_award")
do_load(BasePath .. "prop_union_mall")
do_load(BasePath .. "prop_union_god")
do_load(BasePath .. "prop_resource")
do_load(BasePath .. "prop_resm")
do_load(BasePath .. "prop_resm_num")
do_load(BasePath .. "prop_respawn_lv")
do_load(BasePath .. "prop_respawn_tm")
do_load(BasePath .. "prop_tech")
do_load(BasePath .. "prop_genius")
do_load(BasePath .. "prop_task_detail")
do_load(BasePath .. "prop_equip")
do_load(BasePath .. "prop_online_award")
do_load(BasePath .. "prop_citybuildview")
do_load(BasePath .. "prop_boss_mod_by_date")
do_load(BasePath .. "prop_boss_unlock")
do_load(BasePath .. "prop_boss_level")
do_load(BasePath .. "prop_tw_consume")
do_load(BasePath .. "prop_tw_stage")
do_load(BasePath .. "prop_kw_stage")
do_load(BasePath .. "prop_level")
do_load(BasePath .. "prop_task_daily")
do_load(BasePath .. "prop_task_daily_award")
do_load(BasePath .. "prop_kw_officer")
do_load(BasePath .. "prop_monster_city")
do_load(BasePath .. "prop_mc_stage")
do_load(BasePath .. "prop_lt_stage")
do_load(BasePath .. "prop_lt_reward")

do_load(BasePath .. "prop_black_market")
do_load(BasePath .. "prop_black_market_hot")
do_load(BasePath .. "prop_black_market_hot_group")
do_load(BasePath .. "prop_gacha_group")
do_load(BasePath .. "prop_gacha_piont")
do_load(BasePath .. "prop_gacha_gacha")
do_load(BasePath .. "prop_gacha_world_limit")
do_load(BasePath .. "prop_mall")
do_load(BasePath .. "prop_open_field")
do_load(BasePath .. "prop_altar_buff")
do_load(BasePath .. "prop_vip")
do_load(BasePath .. "prop_mall_item")
do_load(BasePath .. "prop_mall_group_kw")
do_load(BasePath .. "prop_mall_refresh")
do_load(BasePath .. "prop_mall_group_manor")
do_load(BasePath .. "prop_mall_group_monster")
do_load(BasePath .. "prop_mall_group_relic")

do_check("prop_arm")
do_check("prop_build")
do_check("prop_buff")
do_check("prop_effect_type")
do_check("prop_skill")
do_check("prop_hero_basic")
do_check("prop_hero_cure")
do_check("prop_hero_lv_exp")
do_check("prop_hero_quality")
do_check("prop_hero_skill_exp")
do_check("prop_hero_star_up")
do_check("prop_union_power")
do_check("prop_item")
do_check("prop_union_tech")
do_check("prop_union_donate")
do_check("prop_tech")
do_check("prop_task_detail")
do_check("prop_online_award")
do_check("prop_level")
do_check("prop_task_daily")
do_check("prop_task_daily_award")
do_check("prop_gacha_group")
do_check("prop_gacha_piont")
do_check("prop_gacha_gacha")
do_check("prop_gacha_world_limit")

--------------------------------------------------------------------------------
do_load("common/define")


--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- Function : 根据 prop_name，index 获取配置
-- Argument : prop_name, index
-- Return   : table or nil
-- Others   : NULL
--------------------------------------------------------------------------------
function get_conf(prop_name, index)
    if not prop_name or not index then
        ERROR("get_conf: prop_name = %s, index = %s", prop_name or "nil", index or -1 .. "")
        return
    end

    local conf = resmng[prop_name] and resmng[prop_name][index]
    if not conf then
        ERROR("get_conf: lost config. prop_name = %s, index = %s", prop_name or "nil", index or -1 .. "")
        return
    else
        return conf
    end
end


